config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'search#search'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  } #管理者ログイン画面へのルーティング

  devise_for :customers, controllers: {
    sessions: 'public/devise/sessions'
  }


  scope module: :public do
    root to: 'homes#top'
    get 'home/about' => 'homes#about'
    #会員
    resources :customers, only: [:edit, :show, :update]
    #配送先住所
    resources :shipping_addresses, only: [:new, :create, :destroy]
    resources :shipping_address, only: [:edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe_customer' #退会画面へ遷移
    patch '/customers/:id/unsubscribe' => 'customers#switch', as: 'unsubscribe_switch_customer' #会員ステータス切り替え
    get 'shipping_addresses/:id' => 'shipping_address#new'
    post 'shipping_addresses/:id' => 'shipping_address#create'
    post 'shipping_address/:id/destroy' => 'shipping_address#destroy'
    get 'shipping_address/:id/edit' => 'shipping_address#edit'
    patch 'shipping_addresses/:id' => 'shipping_address#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources :shipping_address
    resources :goods, only: [:index, :show]
    resources :cart_items do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders do
      collection do
        post 'confirmation'
        get 'success'
      end
    end
  end


  namespace :admins do
    resources :orders
    patch 'ordered_goods/:id' => 'ordered_goods#update'
    resources :goods
    resources :customers, except: [:destroy]
    resources :genres, except: [:destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/administrato.rb
class Administrato < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  #商品が0の状態で保存変更されるのを防止
  #↓このバリデーションは時間あれば実装する。
  validates :quantity, inclusion: { in: [1,2,3,4,5,6,7,8] }

  belongs_to :good
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}

  has_many :shipping_addresses
  has_many :orders #through: :ordered_good
  has_many :cart_items
  
  def inactive_message
    self.is_deleted? ? super : :special_condition_is_not_valid
  end
  
  def active_for_authentication?
    super && self.is_deleted?
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :goods, dependent: :destroy
end

app/models/good.rb
class Good < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :ordered_goods, dependent: :destroy
  
  belongs_to :genre
  
  attachment :image
  
  validates :name, :introduction, :genre_id, :price, presence: true
  validates :price, numericality: { only_integer: true }
  #価格に数値のみの入力許可のバリデーション、integerのみ
  

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_goods

  validates :shipping_postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  #郵便番号　7桁（ハイフン無し）
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true

  enum payment_method: {クレジットカード:0, 銀行振込:1}
  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

end

app/models/order_good.rb
class OrderGood < ApplicationRecord
  
  validates :quantity, presence: true #数量が空かどうか
  validates :price, presence: true #購入時金額が空かどうか
  validates :production_status, presence: true 
  
  belongs_to :order
  belongs_to :good
  
enum production_status: {着手不可:0,制作待ち:1,製作中:2,製作完了:3}
end

app/models/ordered_good.rb
class OrderedGood < ApplicationRecord
  
  validates :quantity, presence: true #数量が空かどうか
  validates :price, presence: true #購入時金額が空かどうか
  validates :production_status, presence: true

  belongs_to :order
  belongs_to :good

  enum production_status: {着手不可:0,制作待ち:1,製作中:2,製作完了:3}
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    
    #バリデーション、名前、郵便番号、住所
    validates :name, presence: true
    #郵便番号の設定、ハイフンなし、七桁の数字
    validates :shipping_postal_code, presence: true, format: {with: /\A\d{7}\z/}
    validates :shipping_address, presence: true
    
    belongs_to :customer
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)

  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    if customer.update(customer_params)
      redirect_to admins_customer_path(customer.id)
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def add_tax_price(price)
      tax = 1.10
      (price * tax).round
  end
  helper_method :add_tax_price

  def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:is_deleted, :last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :postal_code, :address])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @value = params["search"]["value"]         #データを代入
    @how = params["search"]["how"]             #データを代入
    @datas = search_for(@how, @value)          #def search_forを実行(引数に検索ワードと検索方法)
    @genres = Genre.all
    @genre = Genre.find(@value)
  end

  private

  def match(value)
    #.orを使用することで、valueに一致するカラムのデータをnameカラムとgenre_idカラムから探してきます。
    Good.where(name: value).or(Good.where(genre_id: value))
  end

  def forward(value)                              #forward以降は商品名検索の定義しかしてません。
    Good.where("name LIKE ?", "#{value}%")
  end

  def backward(value)
    Good.where("name LIKE ?", "%#{value}")
  end

  def partical(value)
    Good.where("name LIKE ?", "%#{value}%")
  end


  def search_for(how, value)
    case how                     #引数のhowと一致する処理に進むように定義しています。
    when 'match'                 #ジャンル検索の場合はmatchで固定してるので、必ず'match'の処理に進みます。
      match(value)
    when 'forward'
      forward(value)
    when 'backward'
      backward(value)
    when 'partical'
      partical(value)
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/goods_helper.rb
module Admins::GoodsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admins/customers/edit.html.erb
<div clas="container">
  <div class="row mt-4 ml-5">
    <h4 class="bg-light text-dark ml-5"><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h4>
  </div>
  <div class="row mt-4">
    <div class='col-md-5 mx-auto'>
      <%= form_with model: @customer, url: admins_customer_path(@customer.id), local: true do |f| %>
        <table>
          <tr>
            <th class="text-dark" width="150" height="50">会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th class="text-dark" height="50">氏名</th>
            <td>
              <%= f.text_field :last_name %>
              <%= f.text_field :first_name %>
            </td>
          </tr>
          <tr>
            <th class="text-dark" height="50">フリガナ</th>
            <td>
              <%= f.text_field :last_name_kana %>
              <%= f.text_field :first_name_kana %>
            </td>
          </tr>
          <tr>
            <th class="text-dark" height="50">郵便番号</th>
            <td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <th class="text-dark" height="50">住所</th>
            <td><%= f.text_field :address %></td>
          </tr>
          <tr>
            <th class="text-dark" height="50">電話番号</th>
            <td><%= f.text_field :telephone_number %></td>
          </tr>
          <tr>
            <th class="text-dark" height="50">メールアドレス</th>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <th class="text-dark" height="50">会員ステータス</th>
            <td>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, "有効" %>
              <%= f.radio_button :is_deleted, false  %>
              <%= f.label :is_deleted, "退会" %>
            </td>
          </tr>
        </table>
        <div class="form-group text-center mr-5">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/customers/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="red-border bg-light m-4">会員一覧</h4>
  </div>
  <div class="row mt-4">
    <div class='col-md-8 mx-auto'>
      <table class="table table-hover table-inversey">
        <thead class="bg-light">
          <tr>
            <th class="text-dark">会員ID</th>
            <th class="text-dark">氏名</th>
            <th class="text-dark">メールアドレス</th>
            <th class="text-dark">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admins_customer_path(customer.id) do %>
                <%= customer.last_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <% if customer.is_deleted == true %>
              <td class="text-success">有効</td>
              <% else %>
              <td class="text-secondary">退会</td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class='container mt-5'>
        <div class='row'>
          <div class='mx-auto'>
            <p><%= paginate @customers %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/customers/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="red-border bg-light m-4"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h4>
  </div>

<!--///////////////////会員情報///////////////////-->
  <div class="row mt-4">
    <div class="col">
      <table>
        <tr>
          <th class="text-dark" width="170" height="40">会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th class="text-dark" height="40">氏名</th>
          <td><%= @customer.last_name + " " + @customer.first_name %></td>
        </tr>
        <tr>
          <th class="text-dark" height="40">フリガナ</th>
          <td><%= @customer.last_name_kana + " " + @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th class="text-dark" height="40">郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th class="text-dark" height="40">住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th class="text-dark" height="40">電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th class="text-dark" height="40">メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th class="text-dark" height="40">会員ステータス</th>
          <td>
            <% if @customer.is_deleted == true %>
              <div class="text-success">有効</div>
            <% else %>
              <div class="text-secondary">退会</div>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <!--///////////////////ボタン//////////////////-->
  <div class="row ml-5">
    <div class="m-3">
      <%= link_to "編集", edit_admins_customer_path(@customer.id), class: "btn btn-sm btn-success" %>
    </div>
    <div class="m-3">
      <%= link_to "注文履歴一覧を見る", admins_orders_path, class: "btn btn-sm btn-primary" %>
      <!--仮で全ユーザーの注文一覧画面遷移パス書いてます-->
    </div>
  </div>
</div>

app/views/customers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>