config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'search#search'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  } #管理者ログイン画面へのルーティング

  devise_for :customers, controllers: {
    sessions: 'public/devise/sessions'
  }


  scope module: :public do
    root to: 'homes#top'
    get 'home/about' => 'homes#about'
    #会員
    resources :customers, only: [:edit, :show, :update]
    #配送先住所
    resources :shipping_addresses, only: [:new, :create, :destroy]
    resources :shipping_address, only: [:edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe_customer' #退会画面へ遷移
    patch '/customers/:id/unsubscribe' => 'customers#switch', as: 'unsubscribe_switch_customer' #会員ステータス切り替え
    get 'shipping_addresses/:id' => 'shipping_address#new'
    post 'shipping_addresses/:id' => 'shipping_address#create'
    post 'shipping_address/:id/destroy' => 'shipping_address#destroy'
    get 'shipping_address/:id/edit' => 'shipping_address#edit'
    patch 'shipping_addresses/:id' => 'shipping_address#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources :shipping_address
    resources :goods, only: [:index, :show]
    resources :cart_items do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders do
      collection do
        post 'confirmation'
        get 'success'
      end
    end
  end


  namespace :admins do
    resources :orders
    patch 'ordered_goods/:id' => 'ordered_goods#update'
    resources :goods
    resources :customers, except: [:destroy]
    resources :genres, except: [:destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/administrato.rb
class Administrato < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  #商品が0の状態で保存変更されるのを防止
  #↓このバリデーションは時間あれば実装する。
  validates :quantity, inclusion: { in: [1,2,3,4,5,6,7,8] }

  belongs_to :good
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}

  has_many :shipping_addresses
  has_many :orders #through: :ordered_good
  has_many :cart_items
  
  def inactive_message
    self.is_deleted? ? super : :special_condition_is_not_valid
  end
  
  def active_for_authentication?
    super && self.is_deleted?
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :goods, dependent: :destroy
end

app/models/good.rb
class Good < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :ordered_goods, dependent: :destroy
  
  belongs_to :genre
  
  attachment :image
  
  validates :name, :introduction, :genre_id, :price, presence: true
  validates :price, numericality: { only_integer: true }
  #価格に数値のみの入力許可のバリデーション、integerのみ
  

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_goods

  validates :shipping_postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  #郵便番号　7桁（ハイフン無し）
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true

  enum payment_method: {クレジットカード:0, 銀行振込:1}
  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

end

app/models/order_good.rb
class OrderGood < ApplicationRecord
  
  validates :quantity, presence: true #数量が空かどうか
  validates :price, presence: true #購入時金額が空かどうか
  validates :production_status, presence: true 
  
  belongs_to :order
  belongs_to :good
  
enum production_status: {着手不可:0,制作待ち:1,製作中:2,製作完了:3}
end

app/models/ordered_good.rb
class OrderedGood < ApplicationRecord
  
  validates :quantity, presence: true #数量が空かどうか
  validates :price, presence: true #購入時金額が空かどうか
  validates :production_status, presence: true

  belongs_to :order
  belongs_to :good

  enum production_status: {着手不可:0,制作待ち:1,製作中:2,製作完了:3}
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    
    #バリデーション、名前、郵便番号、住所
    validates :name, presence: true
    #郵便番号の設定、ハイフンなし、七桁の数字
    validates :shipping_postal_code, presence: true, format: {with: /\A\d{7}\z/}
    validates :shipping_address, presence: true
    
    belongs_to :customer
end

app/controllers/admins/goods_controller.rb
class Admins::GoodsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @goods = Good.all.page(params[:page]).per(10)
  end

  def new
    @good = Good.new
    @genres = Genre.all
  end

  def create
    @good = Good.new(good_params)
    @good.save
    redirect_to admins_good_path(@good.id)
  end

  def show
    @good = Good.find(params[:id])
  end

  def edit
    @good = Good.find(params[:id])
    @genres = Genre.all
  end

  def update
    @good = Good.find(params[:id])
    @good.update(good_params)
    redirect_to admins_good_path(@good.id)
  end

  private
  def good_params
    params.require(:good).permit(:name, :genre_id, :introduction, :price, :sales_status, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def add_tax_price(price)
      tax = 1.10
      (price * tax).round
  end
  helper_method :add_tax_price

  def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:is_deleted, :last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :postal_code, :address])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @value = params["search"]["value"]         #データを代入
    @how = params["search"]["how"]             #データを代入
    @datas = search_for(@how, @value)          #def search_forを実行(引数に検索ワードと検索方法)
    @genres = Genre.all
    @genre = Genre.find(@value)
  end

  private

  def match(value)
    #.orを使用することで、valueに一致するカラムのデータをnameカラムとgenre_idカラムから探してきます。
    Good.where(name: value).or(Good.where(genre_id: value))
  end

  def forward(value)                              #forward以降は商品名検索の定義しかしてません。
    Good.where("name LIKE ?", "#{value}%")
  end

  def backward(value)
    Good.where("name LIKE ?", "%#{value}")
  end

  def partical(value)
    Good.where("name LIKE ?", "%#{value}%")
  end


  def search_for(how, value)
    case how                     #引数のhowと一致する処理に進むように定義しています。
    when 'match'                 #ジャンル検索の場合はmatchで固定してるので、必ず'match'の処理に進みます。
      match(value)
    when 'forward'
      forward(value)
    when 'backward'
      backward(value)
    when 'partical'
      partical(value)
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/goods_helper.rb
module Admins::GoodsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admins/goods/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="red-border bg-light m-4">商品編集</h4>
  </div>
  <div class="row mt-4">
    <div class='col-md-5 mx-auto'>
      <%= form_with model: @good, url:admins_good_path(@good.id), local: true do |f| %>
        <table>
          <tr>
            <th class="text-dark" height="50">商品画像</th>
            <td><%= f.attachment_field :image %></td>
          </tr>
          <tr>
            <th class="text-dark" height="50">商品名</th>
            <td>
              <%= f.text_field :name %>
            </td>
          </tr>
          <tr>
            <th class="text-dark" height="50">商品説明</th>
            <td>
              <%= f.text_field :introduction %>

            </td>
          </tr>
          <tr>
            <th class="text-dark" height="50">ジャンル</th>
            <td><%= f.collection_select :genre_id, @genres, :id, :name, {prompt:"--選択してください--"}, class: "form-control" %></td>
          </tr>
          <tr>
            <th class="text-dark" height="50">税抜価格</th>
            <td><%= f.text_field :price %><span>円</span></td>
          </tr>

          <tr>
            <th class="text-dark" height="50">販売ステータス</th>
            <td>
              <%= f.radio_button :sales_status, false %>
              <%= f.label :sales_status, "販売中" %>
              <%= f.radio_button :sales_status, true %>
              <%= f.label :sales_status, "売切れ" %>
            </td>
          </tr>
        </table>
        <div class="form-group text-center mr-5">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/goods/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="red-border bg-light m-4">商品一覧</h4>
    <div class="col text-right">
      <%= link_to new_admins_good_path do %> <!--十字架ボタン（商品作成ページへ）-->
        <i class="fas fa-plus-circle fa-2x"></i>
      <% end %>
    </div>
  </div>
  <div class="row mt-4">
    <div class='col mx-auto'>
      <table class="table table-hover table-inversey">
        <thead class="bg-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @goods.each do |good| %>
            <tr>
              <td><%= good.id %></td>
              <td>
                <%= link_to admins_good_path(good.id) do %>
                  <%= good.name %> <!--商品詳細ページへのリンク-->
                <% end %>
              </td>
              <td class="text-dark"><%= good.price.to_s(:delimited) %></td>
              <td><%= good.genre.name %></td>
              <% if good.sales_status == false %>
                <td class="text-success">販売中</td>
              <% else %>
                <td class="text-secondary">販売停止中</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class='container mt-5'>
        <div class='row'>
          <div class='mx-auto'>
            <p><%= paginate @goods %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/goods/new.html.erb
<div class="container">
  <div class="row mt-4 ml-5">
    <h4 class="bg-light text-dark">商品新規登録</h4>
  </div>
  <div class="row mt-4">
    <div class='col-md-5 mx-auto'>
      <%= form_with model: @good, url: admins_goods_path, local: true do |f| %>
        <table>
          <tr>
            <th class="text-dark" height="50">商品画像</th>
            <td><%= f.attachment_field :image %></td>
          </tr>
           <tr>
            <th class="text-dark" height="50">商品名</th>
            <td><%= f.text_field :name, class:"", placeholder: "商品名" %></td>
          </tr>
          <tr>
            <th class="text-dark" height="50">商品説明</th>
            <td><%= f.text_field :introduction, class:"", placeholder: "ここに説明文を記載します" %></td>
          </tr>
          <tr>
            <th class="text-dark" height="50">ジャンル</th>
            <td><%= f.collection_select :genre_id, @genres.all, :id, :name, {prompt:"--選択してください--"}, class: "form-control", style: "" %></td>
          </tr>
          <tr>
            <th class="text-dark" height="50">税抜価格</th>
            <td><%= f.text_field :price, class:"", placeholder: "1000" %><span>円</span></td>
          </div>
          <tr>
            <th class="text-dark" height="50">販売ステータス</th>
            <td>
              <%= f.radio_button :sales_status, false %>
              <%= f.label :sales_status, "販売中" %>
              <%= f.radio_button :sales_status, true %>
              <%= f.label :sales_status, "売切れ" %>
            </td>
          </tr>
        </table>
        <div class="form-group text-center btn-lg">
          <%= f.submit "新規登録", class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/goods/show.html.erb
<div class="container">
  <div class="row">
    <h4 class=red-border "bg-light m-4">商品詳細</h4>
  </div>
  <div class='row mt-5'>
    <div class="col-md-4">
      <%= attachment_image_tag(@good, :image, fallback: "no_image.jpg", size:"250x170") %>
    </div>
    <div class='col'>
      <table>
        <tr>
      	  <th class="text-dark" width="170" height="40">商品名</th>
      	  <td><%= @good.name %></td>
        </tr>
        <tr>
      	  <th class="text-dark" height="40">商品説明</th>
       	  <td><%= @good.introduction %></td>
        </tr>
        <tr>
          <th class="text-dark" height="50">ジャンル</th>
          <td><%= @good.genre.name %></td>
        </tr>
        <tr>
          <th class="text-dark" height="50">税込価格<br>(税抜価格)</th>
          <td><%= @good.price.to_s(:delimited) %><span>円</span></td>
        </tr>
        <tr>
          <th class="text-dark" height="50">販売ステータス</th>
          <% if @good.sales_status == false %>
            <td class="text-success">販売中</td>
          <% else %>
            <td class="text-secondary">販売停止中</td>
          <% end %>
        </tr>
      </table>
      <div class='row'>
        <div class="col ml-5">
          <%= link_to '編集する',edit_admins_good_path,class: "btn btn-sm btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>