config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'search#search'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  } #管理者ログイン画面へのルーティング

  devise_for :customers, controllers: {
    sessions: 'public/devise/sessions'
  }


  scope module: :public do
    root to: 'homes#top'
    get 'home/about' => 'homes#about'
    #会員
    resources :customers, only: [:edit, :show, :update]
    #配送先住所
    resources :shipping_addresses, only: [:new, :create, :destroy]
    resources :shipping_address, only: [:edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe_customer' #退会画面へ遷移
    patch '/customers/:id/unsubscribe' => 'customers#switch', as: 'unsubscribe_switch_customer' #会員ステータス切り替え
    get 'shipping_addresses/:id' => 'shipping_address#new'
    post 'shipping_addresses/:id' => 'shipping_address#create'
    post 'shipping_address/:id/destroy' => 'shipping_address#destroy'
    get 'shipping_address/:id/edit' => 'shipping_address#edit'
    patch 'shipping_addresses/:id' => 'shipping_address#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources :shipping_address
    resources :goods, only: [:index, :show]
    resources :cart_items do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders do
      collection do
        post 'confirmation'
        get 'success'
      end
    end
  end


  namespace :admins do
    resources :orders
    patch 'ordered_goods/:id' => 'ordered_goods#update'
    resources :goods
    resources :customers, except: [:destroy]
    resources :genres, except: [:destroy]
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_goods

  validates :shipping_postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  #郵便番号　7桁（ハイフン無し）
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true

  enum payment_method: {クレジットカード:0, 銀行振込:1}
  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    #@ordered_goods = OrderedGood.find(params[:id])
    @order.shipping_fee = 800
    @array_order_status = Array.new
    @array_order_status.push(["入金待ち",0],["入金確認",1],["製作中",2],["発送準備中",3],["発送済み",4])
    @array_ordered_good_production_status = Array.new
    @array_ordered_good_production_status.push(["着手不可",0],["制作待ち",1],["製作中",2],["製作完了",3])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_status: params[:order][:order_status].to_i)
      if Order.order_statuses[@order.order_status] == 1
        @order.ordered_goods.each do|f|
          f.update(production_status: 1)
        end
      end
      redirect_to admins_order_path(@order.id)
    end
  end

  private
  #def order_params
    #params.require(:order).permit(:order_status) #permitの中身記述途中
  #end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/views/admins/orders/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="red-border bg-light m-4">注文履歴一覧</h4>
  </div>
  <div class="row mt-4">
    <div class='col-md-8 mx-auto'>
      <table class='table table-hover table-inversey'>
        <thead class="bg-light">
          <tr>
            <th class="text-dark">購入日時</th>
            <th class="text-dark">購入者</th>
            <th class="text-dark">注文個数</th>
            <th class="text-dark">注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td>
                <%= link_to admins_order_path(order) do %>
                  <%= l order.created_at %>
                <% end %>
              </td>
              <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
              <td><%= order.ordered_goods.to_a.sum { |ordered_good| ordered_good.quantity } %></td>
              <td><%= order.order_status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class='container mt-5'>
        <div class='row'>
          <div class='mx-auto'>
            <p><%= paginate @orders %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/orders/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="red-border g-light m-4">注文履歴詳細</h4>
  </div>
  <div class="row mt-4">
    <div class='col'>
      <table>
        <tr>
          <th class="text-dark" width="170" height="40">購入者</th>
          <td>
            <%= link_to admins_customer_path(@order.customer) do %>
             <%= @order.customer.last_name %>
             <%= @order.customer.first_name %>
            <% end %>
          </td>
        </tr>
        <tr>
      	  <th class="text-dark" height="40">購入日</th>
      	  <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
      	  <th class="text-dark" height="40">配送先</th>
      	  <td>
      	    〒<%= @order.customer.postal_code %>
      	    <%= @order.shipping_address %>
      	    </td>
        </tr>
        <tr>
          <th class="text-dark" height="40">支払い方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th class="text-dark" height="40">注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admins_order_path(@order), method: :patch, local: true do |f| %>
            <%= f.select :order_status, @array_order_status, { selected: Order.order_statuses[@order.order_status] } %>
            <%= f.submit "更新", class: "btn btn-success" %>
          </td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>

  <div class='row mt-4'>
    <div class='col-md-8'>
      <table class='table table-hover table-inverse'>
        <thead class="bg-light">
          <tr>
            <th class="text-dark">商品名</th>
            <th class="text-dark">単価(税込)</th>
            <th class="text-dark">数量</th>
            <th class="text-dark">小計</th>
            <th class="text-dark">制作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order.ordered_goods.each do |ordered_good| %>
          <tr>
            <td class="text-dark"><%= ordered_good.good.name %></td>
            <td class="text-dark"><%= ordered_good.price %></td>
            <td class="text-dark"><%= ordered_good.quantity %></td>
            <td class="text-dark">
              <% subtotal_price = (add_tax_price(ordered_good.good.price) * ordered_good.quantity.to_i) %>
              <%= subtotal_price.to_s(:delimited, delimiter: ',') %>
            </td>
            <td>
              <%= form_with model: ordered_good, url: admins_path(order_id: @order.id, id: ordered_good.id), method: :patch, local: true do |f| %>
              <%= f.select :production_status, @array_ordered_good_production_status, { selected: OrderedGood.production_statuses[ordered_good.production_status] } %>
              <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col ml-4">
      <table>
        <tr>
          <th class="text-dark" width="100" height="40">商品合計</th>
          <td class="text-dark"><%= @order.total_price.to_s(:delimited) %><span>円</span></td>
        </tr>
        <tr>
          <th class="text-dark" height="40">配送料</th>
          <td class="text-dark"><%= @order.shipping_fee.to_s(:delimited) %><span>円</span></td>
        </tr>
        <tr>
          <th class="text-dark" height="40">ご請求額</th>
          <td class="text-dark"><%= (@order.total_price + @order.shipping_fee).to_s(:delimited) %><span>円</span></td>
        </tr>
      </table>
    </div>
  </div>
</div>