config/routes.rb
Rails.application.routes.draw do

  get '/search', to: 'search#search'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  } #管理者ログイン画面へのルーティング

  devise_for :customers, controllers: {
    sessions: 'public/devise/sessions'
  }


  scope module: :public do
    root to: 'homes#top'
    get 'home/about' => 'homes#about'
    #会員
    resources :customers, only: [:edit, :show, :update]
    #配送先住所
    resources :shipping_addresses, only: [:new, :create, :destroy]
    resources :shipping_address, only: [:edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe_customer' #退会画面へ遷移
    patch '/customers/:id/unsubscribe' => 'customers#switch', as: 'unsubscribe_switch_customer' #会員ステータス切り替え
    get 'shipping_addresses/:id' => 'shipping_address#new'
    post 'shipping_addresses/:id' => 'shipping_address#create'
    post 'shipping_address/:id/destroy' => 'shipping_address#destroy'
    get 'shipping_address/:id/edit' => 'shipping_address#edit'
    patch 'shipping_addresses/:id' => 'shipping_address#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources :shipping_address
    resources :goods, only: [:index, :show]
    resources :cart_items do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders do
      collection do
        post 'confirmation'
        get 'success'
      end
    end
  end


  namespace :admins do
    resources :orders
    patch 'ordered_goods/:id' => 'ordered_goods#update'
    resources :goods
    resources :customers, except: [:destroy]
    resources :genres, except: [:destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/administrato.rb
class Administrato < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  #商品が0の状態で保存変更されるのを防止
  #↓このバリデーションは時間あれば実装する。
  validates :quantity, inclusion: { in: [1,2,3,4,5,6,7,8] }

  belongs_to :good
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}

  has_many :shipping_addresses
  has_many :orders #through: :ordered_good
  has_many :cart_items
  
  def inactive_message
    self.is_deleted? ? super : :special_condition_is_not_valid
  end
  
  def active_for_authentication?
    super && self.is_deleted?
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :goods, dependent: :destroy
end

app/models/good.rb
class Good < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :ordered_goods, dependent: :destroy
  
  belongs_to :genre
  
  attachment :image
  
  validates :name, :introduction, :genre_id, :price, presence: true
  validates :price, numericality: { only_integer: true }
  #価格に数値のみの入力許可のバリデーション、integerのみ
  

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_goods

  validates :shipping_postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  #郵便番号　7桁（ハイフン無し）
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true

  enum payment_method: {クレジットカード:0, 銀行振込:1}
  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

end

app/models/order_good.rb
class OrderGood < ApplicationRecord
  
  validates :quantity, presence: true #数量が空かどうか
  validates :price, presence: true #購入時金額が空かどうか
  validates :production_status, presence: true 
  
  belongs_to :order
  belongs_to :good
  
enum production_status: {着手不可:0,制作待ち:1,製作中:2,製作完了:3}
end

app/models/ordered_good.rb
class OrderedGood < ApplicationRecord
  
  validates :quantity, presence: true #数量が空かどうか
  validates :price, presence: true #購入時金額が空かどうか
  validates :production_status, presence: true

  belongs_to :order
  belongs_to :good

  enum production_status: {着手不可:0,制作待ち:1,製作中:2,製作完了:3}
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    
    #バリデーション、名前、郵便番号、住所
    validates :name, presence: true
    #郵便番号の設定、ハイフンなし、七桁の数字
    validates :shipping_postal_code, presence: true, format: {with: /\A\d{7}\z/}
    validates :shipping_address, presence: true
    
    belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def add_tax_price(price)
      tax = 1.10
      (price * tax).round
  end
  helper_method :add_tax_price

  def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:is_deleted, :last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :postal_code, :address])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @value = params["search"]["value"]         #データを代入
    @how = params["search"]["how"]             #データを代入
    @datas = search_for(@how, @value)          #def search_forを実行(引数に検索ワードと検索方法)
    @genres = Genre.all
    @genre = Genre.find(@value)
  end

  private

  def match(value)
    #.orを使用することで、valueに一致するカラムのデータをnameカラムとgenre_idカラムから探してきます。
    Good.where(name: value).or(Good.where(genre_id: value))
  end

  def forward(value)                              #forward以降は商品名検索の定義しかしてません。
    Good.where("name LIKE ?", "#{value}%")
  end

  def backward(value)
    Good.where("name LIKE ?", "%#{value}")
  end

  def partical(value)
    Good.where("name LIKE ?", "%#{value}%")
  end


  def search_for(how, value)
    case how                     #引数のhowと一致する処理に進むように定義しています。
    when 'match'                 #ジャンル検索の場合はmatchで固定してるので、必ず'match'の処理に進みます。
      match(value)
    when 'forward'
      forward(value)
    when 'backward'
      backward(value)
    when 'partical'
      partical(value)
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/goods_helper.rb
module Admins::GoodsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ながのCAKE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <!--ヘッダー部-->
    <header class="border-bottom border-dark">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand" href = "/"><span><%= image_tag 'tentative_logo.png', :size => '100x100', class: "rounded-pill" %></span></a>
            <div class="text-middle text-dark">
               <% if admin_signed_in? %>
                 ようこそ、管理者さん！
               <% elsif customer_signed_in? %>
                 ようこそ、<%= current_customer.last_name + current_customer.first_name %>さん！
               <% else %>
                　　　　　　　　　　　　
               <% end %>
            </div>
            
            <div class="offset-md-1" >
              <%= form_with url:search_path, method: :get, local: true do |f| %>
                <%= f.text_field :name, placeholder: '商品を検索' %>
                <%= f.submit '検索' %>
              <% end %>
            </div>
            
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <%if admin_signed_in? %>
                <li class="nav-item mr-3"><%= link_to " 商品一覧", admins_goods_path, class: 'btn btn-outline-secondary text-dark' %></li>
                <li class="nav-item mr-3"><%= link_to " 会員一覧", admins_customers_path, class: 'btn btn-outline-secondary text-dark' %></li>
                <li class="nav-item mr-3"><%= link_to " 注文履歴一覧", admins_orders_path, class: 'btn btn-outline-secondary text-dark' %></li>
                <li class="nav-item mr-3"><%= link_to " ジャンル一覧", admins_genres_path, class: 'btn btn-outline-secondary text-dark' %></li>
                <li class="nav-item mr-3"><%= link_to " ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary text-dark' %></li>
              <% elsif customer_signed_in? %>
                <li class="nav-item mr-3"><%= link_to " マイページ", customer_path(current_customer.id), class: 'btn btn-outline-secondary text-dark' %></li>
                <li class="nav-item mr-3"><%= link_to " 商品一覧", goods_path, class: 'btn btn-outline-secondary text-dark' %></li>
                <li class="nav-item mr-3"><%= link_to " カート", cart_items_path, class: 'btn btn-outline-secondary text-dark' %></li>
                <li class="nav-item mr-3"><%= link_to " ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary text-dark' %></li>
              <% else %>
                <li class="nav-item mr-3"><%= link_to " About", home_about_path, class: 'nav-link m-2 border border-secondary rounded text-dark' %></li>
                <li class="nav-item mr-3"><%= link_to " 商品一覧", goods_path, class: 'nav-link m-2 border border-secondary rounded text-dark' %></li>
                <li class="nav-item mr-3"><%= link_to " 新規登録", new_customer_registration_path, class: 'nav-link m-2 border border-secondary rounded text-dark' %></li>
                <li class="nav-item mr-3"><%= link_to " ログイン", new_customer_session_path, class: 'nav-link m-2 border border-secondary rounded text-dark' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <!--Body部-->
    <%= yield %>
    
    <!--フッター部-->
    <footer class="border-top">
      <div class="container mt-4">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
      <div><%= link_to "関係者用リンク", 'http://abehiroshi.la.coocan.jp/', class: "text-white" %></div>
    </footer>
    
  </body>
</html>